name = "lista_zakupow"
compatibility_date = "2024-02-01"

type = "javascript"

account_id = "f210259cb705a4143ca092969c9de600"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

[build]
command = "npm run build"

[build.upload]
dir = "build"
main = "./index.mjs"
format = "modules"

[vars]
REALM_APPID = "application-0-njhmz"
